name: Execução dos testes de integração

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  integration_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Start containers
        run: docker-compose up -d
      
      - name: Setup Node.js
        uses: actions/setup-node@v2.2.0
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install dependences
        run: yarn
      
      - name: Run tests
        run: yarn actions
      
      - name: Stop containers 
        run: docker-compose down
      
      
